### ISSUE TITLE
heart rate sensor not working

### ISSUE THREAD

**Issue by xonq** [AsteroidOS/meta-bass-hybris#9] opened 2020-01-25 21:11 UTC
Installed asteroid-hrm (demo app), however, the displayed integer is not changing from 0.

Initially tested on 1.0, now on nightly 1.1 (Jan 20th) - both failed

**Comment by xonq** [comment] 2020-01-26 03:57
`test_sensors`: [full output](https://pastebin.com/PyVYdCAF)
```
Name: Heart Rate Monitor
Vendor: QTI
Version: 0x1
Handle: 0x2e
Type: 21
maxRange: 1
resolution: 1
power: 1 mA
minDelay: 0



free(): invalid pointer
Aborted
```

**Comment by MagneFire** [comment] 2020-04-23 16:23
This looks like a duplicate of https://github.com/AsteroidOS/asteroid/issues/107
Can you close this issue?

**Closed as completed** 2020-04-23 19:13 UTC
